// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb0fSmGlAxwjuxYeSh8x11wijwxERJmA8',
    appId: '1:445324070896:web:f35a124fc6b396a6a09735',
    messagingSenderId: '445324070896',
    projectId: 'oraxtech-mynotes',
    authDomain: 'oraxtech-mynotes.firebaseapp.com',
    storageBucket: 'oraxtech-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHS33spDsPb5ecoX8xAJtsiYv944dAco',
    appId: '1:445324070896:android:a95993d422a1fe5aa09735',
    messagingSenderId: '445324070896',
    projectId: 'oraxtech-mynotes',
    storageBucket: 'oraxtech-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWOdPZzjJZV8XHdJqMdFDZa-tH-XLoJc',
    appId: '1:445324070896:ios:818b653253ab1178a09735',
    messagingSenderId: '445324070896',
    projectId: 'oraxtech-mynotes',
    storageBucket: 'oraxtech-mynotes.appspot.com',
    iosClientId: '445324070896-b4gn6h3f98m51e9e83ojb005cphp2v48.apps.googleusercontent.com',
    iosBundleId: 'com.oraxtech.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArWOdPZzjJZV8XHdJqMdFDZa-tH-XLoJc',
    appId: '1:445324070896:ios:818b653253ab1178a09735',
    messagingSenderId: '445324070896',
    projectId: 'oraxtech-mynotes',
    storageBucket: 'oraxtech-mynotes.appspot.com',
    iosClientId: '445324070896-b4gn6h3f98m51e9e83ojb005cphp2v48.apps.googleusercontent.com',
    iosBundleId: 'com.oraxtech.mynotes',
  );
}
